### ISSUE TITLE
When using makepkg on packagebuild it gives error "chgrp: cannot access '/proc/acpi/call': Permission denied"

### ISSUE THREAD

**Issue by mercifulboss** [korikori/ideapad-perf#2] opened 2022-05-02 06:03 UTC
Hello,

I have a lenovo legion 5i running Archlinux and KDE

I can't seem to load the acpi module and no amount of tinkering helps. I am in the 'wheel' group so its strange it doesn't work. Here is what I get when I run the makepkg command:

![image](https://user-images.githubusercontent.com/90151527/166191225-83b268a3-db01-4028-80ae-a122830fd75b.png)

When I run sudo pacman -U ideapad-perf-r10.e1156d1-1-x86_64.pkg.tar.zst I get the following error:

![image](https://user-images.githubusercontent.com/90151527/166191316-f78cc79f-ee4e-4eed-b6db-ea45139ccb31.png)

Am I getting this error because I am using a lenovo legion 5i not an ideapad? (on windows I also had lenovo vantage installed, so I figured it should work as well)

**Comment by korikori** [comment] 2022-05-02 06:10
Hi, thanks for trying this package.
Do you have the `acpi_call` module installed (and loaded)?
edit: you can see if the module is loaded running this
 `lsmod | grep acpi_call`
and if there's no output, you can try loading it with
`modprobe acpi_call` (probably with sudo)

edit 2: 
in answer to your second question - I have no idea if this will do anything for your computer, as they could be completely different, but you should be able to install the package regardless - there are no checks for the underlying architecture during installation.

**Comment by mercifulboss** [comment] 2022-05-02 06:52
Hello, yes I installed acpi-call

Edit: here is the output

![image](https://user-images.githubusercontent.com/90151527/166195843-9f5c2e0e-26a8-4b1c-be35-3b9a40515735.png)

Edit 2: I try to run makepkg again after modprobe

![image](https://user-images.githubusercontent.com/90151527/166196021-bafa463d-75dc-4693-8d5b-30f478e6702e.png)

Edit 3: I reinstalled acpi_call, used sudo modprobe acpi_call and the package successfully built. But now I have a new problem:

![image](https://user-images.githubusercontent.com/90151527/166197437-6fe01ac5-5e42-4711-9fa1-fdc544024cff.png)

**Comment by korikori** [comment] 2022-05-02 07:21
This looks like [another issue](https://github.com/korikori/ideapad-perf/issues/1) reported on KDE - we eventually identified it as a problem with Wayland and how it (does not) handle the system tray. You can try the workaround by running the following as one line in the terminal:
`GDK_BACKEND=x11 ideapad-perf-tray.rb`

If this works for you, the reporter of the other issue has added some KDE-specific instructions that may be helpful to you: (https://github.com/korikori/ideapad-perf/issues/1#issuecomment-1096787193) 

If this works, do let me know if the script actually does anything for the performance modes on your computer, and I will add it as a supported model. You should be able to run the CLI tool without the applet anyway - executing the following command should return the current values for your system performance and battery charge modes:

`ideapad-perf -c` 
 
If this returns empty output and/or errors, your laptop is using different ACPI calls and this tool will be useless to you without further modification.

**Comment by mercifulboss** [comment] 2022-05-02 15:07
> This looks like [another issue](https://github.com/korikori/ideapad-perf/issues/1) reported on KDE - we eventually identified it as a problem with Wayland and how it (does not) handle the system tray. You can try the workaround by running the following as one line in the terminal: `GDK_BACKEND=x11 ideapad-perf-tray.rb`
> 
> If this works for you, the reporter of the other issue has added some KDE-specific instructions that may be helpful to you: ([#1 (comment)](https://github.com/korikori/ideapad-perf/issues/1#issuecomment-1096787193))
> 
> If this works, do let me know if the script actually does anything for the performance modes on your computer, and I will add it as a supported model. You should be able to run the CLI tool without the applet anyway - executing the following command should return the current values for your system performance and battery charge modes:
> 
> `ideapad-perf -c`
> 
> If this returns empty output and/or errors, your laptop is using different ACPI calls and this tool will be useless to you without further modification.

Hello, running the command above gives me the same errors:

![image](https://user-images.githubusercontent.com/90151527/166257874-d24d07db-1ff1-47d7-b8ff-e4a27813291d.png)

Also, when I run the `ideapad-perf -c` command here is what I get:
![image](https://user-images.githubusercontent.com/90151527/166257988-03f1e193-68c6-4e56-8c9b-300773e38b18.png)


Perhaps I need to set a battery mode first?

**Comment by korikori** [comment] 2022-05-04 10:27
No, I am afraid that the errors that you receive from the CLI tool mean that your laptop model is not using the same ACPI calls, meaning that it is not compatible with this script. If you can find the ACPI calls for your model, I could modify the script for you. You can also consider trying out https://github.com/0xless/battmngr as well.

**Comment by korikori** [comment] 2022-05-10 15:20
@mercifulboss can you provide me with the exact model number/modification, CPU, etc? Does the laptop have a page in the Arch Wiki or some similar resource? Thanks in advance.

**Comment by mercifulboss** [comment] 2022-05-10 16:51
> @mercifulboss can you provide me with the exact model number/modification, CPU, etc? Does the laptop have a page in the Arch Wiki or some similar resource? Thanks in advance.

Here is my information: 

![image](https://user-images.githubusercontent.com/90151527/167681482-4072bad2-56bd-4b5a-abe7-a493ad4d6f4d.png)

Please let me know if you need anything else. And thank you for taking the time.


Edit: There is an archwiki page (Lenovo Legion 5i) however, its not very in depth:
https://wiki.archlinux.org/title/Laptop/Lenovo#Legion_series

**Comment by korikori** [comment] 2022-05-10 20:29
So this is an Intel system, and the two confirmed models that work with these acpi calls that I'm using are both AMD, so I have low expectations. I searched around for the Legion series, but I can't find its set of acpi calls online. The closest I can identify is the T14 Gen 1, which uses a very similar CPU - https://wiki.archlinux.org/title/Lenovo_ThinkPad_T14/T14s_(Intel)_Gen_1.

This article contains ACPI calls to _set_ the performance mode, but not to check it - so the script will have to be extensively modified to work on your system, and also it won't work with the tray (cause it has to check for the performance mode before it can show it). And anyway we still haven't solved displaying the applet on your device, but that may be due to the CLI tool being unusable.

Please try the ACPI calls in that article and see if they do anything - there is an example command to enable the performance mode, and a convoluted solution to checking if it is enabled via `nvidia-settings`. If this works, I'll see in making a CLI tool for you.

**Comment by korikori** [comment] 2022-05-10 20:31
And if these _don't_ work for you, you might want to go down the rabbit hole of reverse engineering your acpi calls yourself. You can take a look at this project for a good rundown on how to approach that: https://github.com/MatMercer/lenovo-power-manager

**Comment by mercifulboss** [comment] 2022-05-10 20:43
> So this is an Intel system, and the two confirmed models that work with these acpi calls that I'm using are both AMD, so I have low expectations. I searched around for the Legion series, but I can't find its set of acpi calls online. The closest I can identify is the T14 Gen 1, which uses a very similar CPU - https://wiki.archlinux.org/title/Lenovo_ThinkPad_T14/T14s_(Intel)_Gen_1.
> 
> This article contains ACPI calls to _set_ the performance mode, but not to check it - so the script will have to be extensively modified to work on your system, and also it won't work with the tray (cause it has to check for the performance mode before it can show it). And anyway we still haven't solved displaying the applet on your device, but that may be due to the CLI tool being unusable.
> 
> Please try the ACPI calls in that article and see if they do anything - there is an example command to enable the performance mode, and a convoluted solution to checking if it is enabled via `nvidia-settings`. If this works, I'll see in making a CLI tool for you.

When launching the command nothing appears on the command line. Indeed, I have tried these commands before and I would continuously get the error seen below - I was not able to find a solution for the error online:
![image](https://user-images.githubusercontent.com/90151527/167718757-fb981e53-c361-439a-a92d-bce038202f90.png)



However I managed to use the following command to halt my battery charge at 56%:

`sudo sh -c "echo 1 > /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"`

This is where I got the command from:
https://www.reddit.com/r/Ubuntu/comments/pz9vys/is_there_an_alternative_to_the_lenovo_vantage/

In particular I'd like to point out the comment by SeriousBroccoli
![image](https://user-images.githubusercontent.com/90151527/167717931-02d747a9-29b1-48ab-b8be-2715802fa7f7.png)

I am not sure if this is any help at all. However, this command sometimes breaks (when I switch performance modes) so I have to keep using this command in order to have the icon in the system tray say 56% charge (not sure if its actually preventing the battery from charging or just updates the icon to say a different value).

I was hoping there could be a simple convenient tool like we have on windows like lenovo vantage, where clicking a button would not allow the battery to charge above 56% and then turning it off will allow it to charge fully. Unfortunately I am not a programmer and lack the knowledge to build my own GUI tool (otherwise I would have done so by now).

Edit: Commands with `sudo tee` do not work on my system. The command below does not work:
`echo 1 | sudo tee /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode`

Only the commands I posted earlier seem to have some sort of effect. I am not sure why.

**Comment by korikori** [comment] 2022-05-10 22:13
Yes, the battery conservation/rapid charge commands appear to be similar across ideapad devices and there is even a kernel driver to control them so you don't even need acpi calls for that. Are you only interested in this part of the script? I was under the impression that we were after the other performance modes (low power, balanced and performance). 

If you only need the battery script, I can try and prepare something for you.

As a side note, do you have these two files - try running

`cat /sys/firmware/acpi/platform_profile_choices`
and
`cat /sys/firmware/acpi/platform_profile`

**Comment by mercifulboss** [comment] 2022-05-10 22:17
> Yes, the battery conservation/rapid charge commands appear to be similar across ideapad devices and there is even a kernel driver to control them so you don't even need acpi calls for that. Are you only interested in this part of the script? I was under the impression that we were after the other performance modes (low power, balanced and performance).
> 
> If you only need the battery script, I can try and prepare something for you.
> 
> As a side note, do you have these two files - try running
> 
> `cat /sys/firmware/acpi/platform_profile_choices` and `cat /sys/firmware/acpi/platform_profile`

I was interested in being able to easily control between different performance modes when taking my laptop with me (but use only one atm due to the inconvenience of switching between them).

It does not seem that the commands you posted work:
![image](https://user-images.githubusercontent.com/90151527/167730780-9e3cbea9-3528-4300-87ee-54832be598b4.png)

**Comment by korikori** [comment] 2022-05-10 22:40
Can you test this: https://github.com/korikori/ideapad-perf/releases/tag/r26.2f450da
You would still have to call the applet with `GDK_BACKEND=x11 ideapad-perf-tray.rb`

**Comment by mercifulboss** [comment] 2022-05-11 00:52
> Can you test this: https://github.com/korikori/ideapad-perf/releases/tag/r26.2f450da You would still have to call the applet with `GDK_BACKEND=x11 ideapad-perf-tray.rb`

When I use the package build I get an error when trying to launch the application:
![image](https://user-images.githubusercontent.com/90151527/167747708-49113491-0a8f-4d69-8ac8-8ea8cfb94dbf.png)

When installing from the tarbell, it freezes as seen below:
![image](https://user-images.githubusercontent.com/90151527/167747119-66de17ac-2657-4e90-b2f3-805b13b41c4c.png)

But I also get an icon in the tray:
![image](https://user-images.githubusercontent.com/90151527/167747223-300b28ee-bbd2-46a0-8430-4cce620e5367.png)

On right click I get a popup that says "Rapid Charge, Battery Conservation, Off". But when I turn off the konsole, the icon disappears. Launching it without running the command again doesn't work.

**Comment by korikori** [comment] 2022-05-11 01:02
The second screenshot is not "freezing" - the applet has no terminal output, it is only supposed to create the icon in your tray, so this is expected behavior. If you run it with an ampersand (&) character in the end, like so
`GDK_BACKEND=x11 ideapad-perf-tray.rb &`
it will run independently from your terminal session (so closing the terminal won't close the applet).

You can create a shortcut/alias to this command so that you don't have to start it from the terminal. In this [other issue](https://github.com/korikori/ideapad-perf/issues/1#issuecomment-1096787193) @suspycat has provided some instructions for this on KDE.

Anyway, what I'd like to know is 1) whether the applet/CLI functionality works in changing the battery states for you, and 2) whether this solves your issue. Thanks.

**Comment by mercifulboss** [comment] 2022-05-11 01:15
> The second screenshot is not "freezing" - the applet has no terminal output, it is only supposed to create the icon in your tray, so this is expected behavior. If you run it with an ampersand (&) character in the end, like so `GDK_BACKEND=x11 ideapad-perf-tray.rb &` it will run independently from your terminal session (so closing the terminal won't close the applet).
> 
> You can create a shortcut/alias to this command so that you don't have to start it from the terminal. In this [other issue](https://github.com/korikori/ideapad-perf/issues/1#issuecomment-1096787193) @Suspycat has provided some instructions for this on KDE.
> 
> Anyway, what I'd like to know is 1) whether the applet/CLI functionality works in changing the battery states for you, and 2) whether this solves your issue. Thanks.

I am not clear on what is meant by "adding GDK_BACKEND=x11 before the script path"...where exactly do I end GDK_BACKEND=x11?
![image](https://user-images.githubusercontent.com/90151527/167749436-04063cbe-70f5-4fb7-8994-84c00797409c.png)

Also, through the CLI, the applet does not seem to do anything - I can press on the radio buttons but the battery doesn't start charging. Could it be because of an interaction with powertoolsdaemon?

**Comment by korikori** [comment] 2022-05-11 01:22
1. As far as I understand the instructions and what I see on the screen, you should enter GDK_BACKEND=x11 before the path to the script in the Command field. Please note that I am not running KDE and I did not write these instructions so those are my guesses.
2. Can you clarify as the CLI and the applet are different. Can you try this in a terminal:
`ideapad-perf -c`
this should give some output on the current battery charging mode.
`ideapad-perf -b rc` 
this should set the charging mode to Rapid Charge; similarly
`ideapad-perf -b bs` 
should set the charging mode to Battery Saving.

**Comment by mercifulboss** [comment] 2022-05-11 04:22
> 



> 1. As far as I understand the instructions and what I see on the screen, you should enter GDK_BACKEND=x11 before the path to the script in the Command field. Please note that I am not running KDE and I did not write these instructions so those are my guesses.
> 2. Can you clarify as the CLI and the applet are different. Can you try this in a terminal:
>    `ideapad-perf -c`
>    this should give some output on the current battery charging mode.
>    `ideapad-perf -b rc`
>    this should set the charging mode to Rapid Charge; similarly
>    `ideapad-perf -b bs`
>    should set the charging mode to Battery Saving.

I tried adding the command GDK_BACKEND=x11 but I dont think it does anything

Here is the output of all the commands you listed:
![image](https://user-images.githubusercontent.com/90151527/167768584-cd66b61e-8390-4be1-adb2-8db7fcf22709.png)

**Comment by korikori** [comment] 2022-05-19 13:46
1) the mode for conservation mode should be different, sorry for providing `bs` before:
`ideapad-perf -b bc`
2) at this point it is possible that the script is setting the computer into rapid charge/bc mode, but it can't read the status correctly. You should be able to determine this by booting into Windows (the mode should be preserved), or just by monitoring usage - rapid charge charges the battery in around one hour, whereas when Battery Conservation is enabled, you can't charge the battery over 60% or so.
3) I am afraid that I won't be able to do much more about this on your computer. I have no way to test it as I have no access to your computer, but as stated previously, I expect that the platforms are different enough that this won't work there without further (heavier) modification. I'm sorry.

**Comment by mercifulboss** [comment] 2022-05-25 16:30
Pardon the late reply. I've been rather busy lately. I don't have windows installed on this computer anymore. Made the transition to linux fully :)

But I know that my battery conservation mode works when using the following commands:

`sudo sh -c "echo 1 > /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"`

`sudo sh -c "echo 0 > /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"`

As was mentioned in this link:
https://www.reddit.com/r/Ubuntu/comments/pz9vys/is_there_an_alternative_to_the_lenovo_vantage/

It seems this applies to both ideapad and legion laptops (they both use vantage in windows as far as i know), so I'm surprised your script can't read the battery mode.

Would it be possible to somehow add in the above commands into the gui interface so that they automatically switch when clicked?

Also, batter conservation seems to work after installing `power-profiles-daemon` - i was wondering if it has any relation to your app?  (https://gitlab.freedesktop.org/hadess/power-profiles-daemon)

**Comment by korikori** [comment] 2022-05-25 17:55
Before going further, can you tell me what happens when you run
 `ideapad-perf -b bc` 
does it enable the 60% threshold?

**Comment by mercifulboss** [comment] 2022-05-25 18:07
Here is the output:

![image](https://user-images.githubusercontent.com/90151527/170335287-3a46994c-e65e-483a-b92e-5bf3db591b69.png)

However, the 60% charge threshold is enabled, but i'm not sure if its power-profiles-daemon doing that or this. And I only think its enabled because the battery charge has been stuck at 59% for the past hour though it seems to always say charging.

**Comment by korikori** [comment] 2022-05-26 08:23
Can you disable power-profiles-daemon and/or switch to the other performance mode so that we can know if this works or not?

**Comment by mercifulboss** [comment] 2022-05-26 15:58
![image](https://user-images.githubusercontent.com/90151527/170526575-ac6a7122-771f-4eb7-b573-4ce0d7b6c57a.png)

I uninstalled power-profile-deamon and disabled tlp. Here is the result.

**Comment by mercifulboss** [comment] 2022-05-26 16:57
After some further testing, it seems that neither TLP nor Power-profiles-daemon do anything. 
![image](https://user-images.githubusercontent.com/90151527/170536651-2e95dc1d-38b7-4de9-aa88-93d0b702de67.png)

Running the command:
`sudo sh -c "echo 0 > /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"` causes the laptop to start charging again

And 
`sudo sh -c "echo 1 > /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"` prevents any charging from occurring. The laptop is trying to continue to charge but is stuck at the threshold that is set in the /sys/class/power_supply/BAT0/ folder. This is evident from the battery charging indicator but the charge percentage doesn't increase.

**Comment by korikori** [comment] 2022-06-08 13:48
I'm sorry but I still don't understand if running `ideapad-perf -b bc` (or the other mode) does anything for you. Please disregard the output and check for any other signs of change - such as 'the battery charging indicator but the charge percentage doesn't increase' as you have stated. Thanks again and sorry for the delayed replies.

Basically at this point I know that the script doesn't read the status correctly on your system, the question is whether it can change it - cause we can change reading the status fairly easily, but changing the status by writing to a file in /sys/bus/platform/drivers/ideapad_acpi is very different than what the current script is doing, and this would result in a different project, new udev rules, etc.

**Comment by korikori** [comment] 2022-09-17 11:53
I am closing this issue for now as I don't expect to work on it further for the time being. Feel free to reopen it if you have new information that may be helpful.

**Closed as completed by korikori** 2022-09-17 11:53 UTC
Labels: enhancement, wontfix
